### Q1. Infinite Norm
Compute the infinite norm of the following matrix

2	-2	1<br>
-1	2	-1<br>
2	-4	1

In [1]:
import numpy as np

In [2]:
a = np.array([[2,-2,1],[-1,2,-1],[2,-4,1]])

In [3]:
print(a)

[[ 2 -2  1]
 [-1  2 -1]
 [ 2 -4  1]]


In [4]:
linf = np.linalg.norm(a, ord = np.inf)

In [5]:
print(linf)

7.0


### Q2. Frobenius Norm
The L2 norm is also called as Frobenius norm. Compute the Frobenius norm of the following matrix

2	-2	1<br>
-1	2	-1<br>
2	-4	1

In [6]:
l2 = np.linalg.norm(a)

In [7]:
print(l2)

6.0


### Q3. Matrix Multiplication
Let A matrix be

1	-3	4<br>
-2	10	-7<br>
0	1	0<br>
0	0	0

Let B matrix be

5	0<br>
-2	11<br>
-3	12

Which of the following matrices is equal to the matrix AB ?

In [9]:
A = np.array([[1,-3,4],[-2,10,-7],[0,1,0],[0,0,0]])

In [10]:
B = np.array([[5,0],[-2,11],[-3,12]])

In [11]:
print(np.dot(A,B))

[[-1 15]
 [-9 26]
 [-2 11]
 [ 0  0]]


<h3>Q4. Broadcasting</h3><br>
What is the motivation behind broadcasting?

(a) It copies array data to arrays of appropriate shapes so they may be combined.

(b) It saves computational time by spreading operations over different CPUs

(c) Both are correct

(d) None of the above is correct

Answer - (c)

<h3>Q5. Square Matrices</h3><br>
Let A and B be two 3x3 matrix then which of the following is true?

(a) if C=A*B then C will be a 6X6 matrix

(b) If v is a 3 dimensional vector then A * B * v is a 3 dimensional matrix

(c) A * B * A = B * A * B

Answer - (b)