### 1. Importing numpy Library

In [1]:
import numpy as np

### 2. Creating numpy nd-Array

In [2]:
a = np.array([1,2,3,4])

In [3]:
print(a)

[1 2 3 4]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


### 3. shape - The shape property is usually used to get the current shape(dimensions) of an array.

In [5]:
a.shape

(4,)

In [8]:
b = np.array([[1,2,3,4],[5,6,7,8]])

In [9]:
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
print(b.shape)

(2, 4)


### 4. Transpose of an array

In [11]:
b.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### 5. Dot Product/ Cross Product

In [12]:
np.dot(b,b.T)

array([[ 30,  70],
       [ 70, 174]])

### 6. Creating a Random Array

In [14]:
np.random.randint?

In [15]:
np.random.randint(60,100,10)

array([68, 70, 88, 71, 94, 79, 75, 99, 73, 66])

In [16]:
np.random.randint(60,100,(5,5))

array([[77, 97, 83, 78, 82],
       [94, 93, 80, 71, 85],
       [66, 88, 68, 81, 63],
       [60, 84, 71, 94, 80],
       [74, 74, 62, 96, 71]])

### 7. Finding Maximum and Minimum Element in an Array

In [19]:
matrix = np.random.randint(60,100,(5,5))

In [20]:
print(matrix)

[[86 79 78 89 84]
 [77 98 93 75 80]
 [91 78 98 86 99]
 [60 91 90 89 70]
 [80 68 65 76 65]]


In [21]:
np.max(matrix)

99

In [22]:
np.min(matrix)

60

### 8. Index of Maximum and Minimum Elements in an Array

In [23]:
np.argmax(matrix)

14

In [24]:
np.argmin(matrix)

15

In [25]:
c = np.array([0,1,2,-8,6,8,20])

In [26]:
np.argmin(c)

3

In [27]:
np.argmax(c)

6

### 9. Getting all the Unique Elements of an Array.

In [28]:
d = np.array([0,1,10,10,2,-8,6,6,6,6,8,10])

In [29]:
print(np.unique(d))   # Returns an array of unique elements from given array in a sorted order.

[-8  0  1  2  6  8 10]


### 10. Counting the occurance of each unique element

In [30]:
print(np.unique(d,return_counts = True))

(array([-8,  0,  1,  2,  6,  8, 10]), array([1, 1, 1, 1, 4, 1, 3], dtype=int64))


### 11. Problem Statement: Program to find out the element with the highest frequency in the given array.

In [31]:
a = np.unique(d,return_counts = True)

In [32]:
print(a[0])

[-8  0  1  2  6  8 10]


In [33]:
pos = np.argmax(a[1])

In [34]:
print(a[0][pos]) # Element that occur maximum no. of times in the array d

6


### 12. Slicing of Array

In [35]:
matrix[2:4, 1:4]

array([[78, 98, 86],
       [91, 90, 89]])

In [36]:
matrix[2,1]

78

In [37]:
matrix[2: , 1: ]

array([[78, 98, 86, 99],
       [91, 90, 89, 70],
       [68, 65, 76, 65]])